apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kisanvani-gcp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shivam2003-dev/kisan-alert-track-4.git
    targetRevision: main
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: kisanvani
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
